[package]
name = "model-checking"
version = "0.1.0"
edition = "2021"

[dependencies]
ananke-bdd = { path = "../../ananke-bdd" }
color-eyre = "0.6"
clap = { version = "4.5", features = ["derive"] }
log = "0.4"
simplelog = "0.12"
num-bigint = "0.4"
num-traits = "0.2"
