[package]
name = "feature_model"
version = "0.1.0"
edition = "2021"

[dependencies]
bdd-rs = { path = "../.." }
clap = { version = "4.5", features = ["derive"] }
color-eyre = "0.6"
simplelog = "0.12"
log = "0.4"
num-bigint = "0.4"
