[package]
name = "symbolic-execution"
version = "0.1.0"
edition = "2021"

[dependencies]
ananke-bdd = { path = "../../ananke-bdd" }
clap = { version = "4.5", features = ["derive"] }
color-eyre = "0.6"
